# Copyright 2026 HM Revenue & Customs
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

include "frontend.conf"

appName = "message-frontend"
play.http.router = prod.Routes

play.i18n.langs = ["en", "cy"]

# Provides an implementation of AuditConnector. Use `uk.gov.hmrc.play.bootstrap.AuditModule` or create your own.
# An audit connector must be provided.
play.modules.enabled += "uk.gov.hmrc.play.bootstrap.AuthModule"

play.modules.enabled += "uk.gov.hmrc.play.bootstrap.HttpClientV2Module"

# Metrics plugin settings - graphite reporting is configured on a per env basis
metrics.enabled = true

microservice {
  services {
    secure-message {
      protocol = http
      host = localhost
      port = 9051
    }
    auth {
      host = localhost
      port = 8500
    }

    datastream {
      host = localhost
      port = 8100
    }
    secure-message-frontend {
      host = localhost
      port = 9055
    }

    auth-login-api {
      host = localhost
      port = 8585
    }
  }
}
